# defines dynamic dirs where config part should be added
- env:
    nvim_dyndir: $dyndir/nvim
    nvim_runtime: $dyndir/config
    nvim_lua: $nvim_runtime/lua
    nvim_init: $nvim_dyndir/init.lua.d
    nvim_chadrc: $nvim_dyndir/chadrc.lua.d
    nvim_mappings: $nvim_dyndir/mappings.lua.d
    nvim_options: $nvim_dyndir/options.lua.d

# generate the neovim files and link them in user home
- defer:
    id: neovim_conf_gen
    tasks:
      - concat:
          $nvim_runtime/init.lua: $nvim_init
          $nvim_lua/chadrc.lua: $nvim_chadrc
          $nvim_lua/mappings.lua: $nvim_mappings
          $nvim_lua/options.lua: $nvim_options
      - link:
          ~/.config/nvim:
            create: true
            path: $nvim_runtime
