- defaults:
    link:
      force: false
      create: true
      relink: true
    concat:
      create: true

- clean: ['~']

- env:
    dyndir: .dynamic    # directories used to store dynamically generated files

