
# defines dynamic dirs where config part should be added
- env:
    vimrc: $dyndir/vimrc.d
    vim_runtime: $dyndir/vim

# generate the bash files and link them in user home
- defer:
    id: vim_conf_gen
    tasks:
      - concat:
          $dyndir/vimrc: $vimrc
      - link:
          ~/.vimrc: $dyndir/vimrc
          ~/.vim: $vim_runtime

      # Ensure generation of vim tags
      - shell:
        - command: >-
            vim
            '+helptags ALL'
            '+qall'
          description: Generate help tags for vim plugins
          quiet: true

        - command: >-
            vim
            '+mkspell ~/.vim/spell/fr.utf-8.add'
            '+mkspell ~/.vim/spell/en.utf-8.add'
            '+qall'
          description: Generate vim spelling dictionaries
          quiet: true
