# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# load each config parts
#   - definitions: defines variables for the rest
#   - aliases: defines bash aliases
#   - functions: defines bash functions
#   - prompt: defines the prompt
#   - services: ensure some services are started (e.g. ssh agent)
#   - local: allow local override of the bashrc
for config in definitions aliases functions prompt services local; do
  if [ -e "$HOME/.bash_$config" -a -r "$HOME/.bash_$config" ]; then
    source "$HOME/.bash_$config"
  fi
done

# Display the logo for login shells
if shopt -q login_shell && [ -e "$HOME/.logo" -a -r "$HOME/.logo" ] ; then
  cat "$HOME/.logo"
fi

########################
# Configuration for bash
########################
#
# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
shopt -s globstar

# enable programmable completion features
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi
