# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# load each config parts
#   - definitions: defines variables for the rest
#   - aliases: defines bash aliases
#   - functions: defines bash functions
#   - prompt: defines the prompt
#   - services: ensure some services are started (e.g. ssh agent)
#   - local: allow local override of the bashrc
for config in definitions aliases functions prompt services local; do
  if [ -e "$HOME/.bash_$config" -a -r "$HOME/.bash_$config" ]; then
    source "$HOME/.bash_$config"
  fi
done

# Display the logo for login shells
if shopt -q login_shell && [ -e "$HOME/.logo" -a -r "$HOME/.logo" ] ; then
  cat "$HOME/.logo"
fi

